import { BASE_POSITION, FINISH_GATE_LOCAL_POSITION, TRACK_SIZE } from "./constants";
import { evaluateState } from "./ai";
import { executeMove } from "./executor";
import { getLegalMoves, type LegalMove } from "./legalMoves";
import type { CardRank, GameState, Marble, PlayerId, TeamId } from "./types";

function teamOwners(state: GameState, team: TeamId): PlayerId[] { return state.players.filter(p => p.team === team).map(p => p.id); }
function finishedCount(state: GameState, team: TeamId): number { const owners=teamOwners(state,team); return state.marbles.filter(m=>owners.includes(m.owner)&&m.zone==="FINISH").length; }
function homeCount(state: GameState, team: TeamId): number { const owners=teamOwners(state,team); return state.marbles.filter(m=>owners.includes(m.owner)&&m.zone==="HOME").length; }
function relativeProgress(m: Marble): number { if(m.zone!=="TRACK"||m.trackPosition===null)return -1; return (m.trackPosition-BASE_POSITION[m.owner]+TRACK_SIZE)%TRACK_SIZE; }
function strategicTrackValue(m:Marble):number{const p=relativeProgress(m);if(p<0)return 0;const near=FINISH_GATE_LOCAL_POSITION-3;if(p>=FINISH_GATE_LOCAL_POSITION)return 70;if(p>=near)return 50+(p-near)*20;if(p>=FINISH_GATE_LOCAL_POSITION-11)return 15+(p-(FINISH_GATE_LOCAL_POSITION-11))*5;return p*.45;}
function teamProgress(state: GameState, team: TeamId): number { const owners=teamOwners(state,team); return state.marbles.filter(m=>owners.includes(m.owner)).reduce((s,m)=>s+(m.zone==="FINISH"?80+(m.finishPosition??0)*8:m.zone==="TRACK"?relativeProgress(m):0),0); }
function exposedThreat(state: GameState, team: TeamId): number { const enemyOwners=teamOwners(state,team===0?1:0),ownOwners=teamOwners(state,team);let danger=0;for(const mine of state.marbles.filter(m=>ownOwners.includes(m.owner)&&m.zone==="TRACK"&&m.trackPosition!==null)){if(mine.trackPosition===BASE_POSITION[mine.owner])continue;for(const enemy of state.marbles.filter(m=>enemyOwners.includes(m.owner)&&m.zone==="TRACK"&&m.trackPosition!==null)){const d=(mine.trackPosition!-enemy.trackPosition!+TRACK_SIZE)%TRACK_SIZE;if(d>=1&&d<=13)danger+=14-d;}}return danger; }
function enemyArrivalThreat(state: GameState, team: TeamId): number { const enemy=(team===0?1:0) as TeamId; const owners=teamOwners(state,enemy); const finished=finishedCount(state,enemy); let t=finished*35; for(const m of state.marbles.filter(x=>owners.includes(x.owner)&&x.zone==="TRACK")){const p=relativeProgress(m); if(p>=FINISH_GATE_LOCAL_POSITION-3)t+=(p-(FINISH_GATE_LOCAL_POSITION-4))*18; else if(p>=FINISH_GATE_LOCAL_POSITION-11)t+=(p-(FINISH_GATE_LOCAL_POSITION-12))*5;} if(finished===7)t*=4; return t; }
function cardRank(state: GameState, player: PlayerId, move: LegalMove): CardRank | undefined { return state.players.find(p=>p.id===player)?.hand.find(c=>c.id===move.cardId)?.rank; }
function special(rank: CardRank|undefined){return rank==="4"||rank==="7"||rank==="J";}
function newlyArrived(before:GameState,after:GameState,team:TeamId){const owners=teamOwners(before,team);let n=0;for(const a of after.marbles){if(!owners.includes(a.owner)||a.zone!=="FINISH")continue;const b=before.marbles.find(m=>m.id===a.id);if(b&&b.zone!=="FINISH")n++;}return n;}
export function chooseStrategicMove(state: GameState, player: PlayerId = state.currentPlayer): LegalMove {
  if(player!==state.currentPlayer)throw new Error("AI can only choose for current player"); const moves=getLegalMoves(state,player);if(!moves.length)throw new Error("No legal move");
  const team=state.players.find(p=>p.id===player)!.team,enemy=(team===0?1:0) as TeamId;const before={finish:finishedCount(state,team),enemyHome:homeCount(state,enemy),progress:teamProgress(state,team),enemyProgress:teamProgress(state,enemy),danger:exposedThreat(state,team),threat:enemyArrivalThreat(state,team)};const hasOrdinaryAlternative=moves.some(m=>!special(cardRank(state,player,m)));let best=moves[0],bestScore=-Infinity;
  for(const move of moves){const after=executeMove(state,move);if(after.winner===team)return move;const rank=cardRank(state,player,move),ownFinishGain=finishedCount(after,team)-before.finish,arrivals=newlyArrived(state,after,team),captures=homeCount(after,enemy)-before.enemyHome,progressGain=teamProgress(after,team)-before.progress,enemyProgressLoss=before.enemyProgress-teamProgress(after,enemy),threatRemoved=before.threat-enemyArrivalThreat(after,team),dangerRemoved=before.danger-exposedThreat(after,team);let score=evaluateState(after,player)*.25;score+=ownFinishGain*5000+arrivals*2500+captures*95+progressGain*4+enemyProgressLoss*5+threatRemoved*7+dangerRemoved*2;const owners=teamOwners(state,team),beforeCompleted=owners.filter(o=>state.marbles.filter(m=>m.owner===o&&m.zone==="FINISH").length===4).length,afterCompleted=owners.filter(o=>after.marbles.filter(m=>m.owner===o&&m.zone==="FINISH").length===4).length;score+=(afterCompleted-beforeCompleted)*1800;if(move.type==="EXIT")score+=180;const immediateBenefit=captures>0||ownFinishGain>0||threatRemoved>0||progressGain>=10||dangerRemoved>=5;if(hasOrdinaryAlternative&&!immediateBenefit){if(rank==="4")score-=120;if(rank==="7")score-=180;if(rank==="J")score-=140;}if(rank==="7"&&move.type==="SEVEN"){score-=(move.parts.length-1)*35;if(arrivals>0)score+=900;if(captures>0)score+=300;}if(rank==="J"&&move.type==="JACK"){const sb=state.marbles.find(m=>m.id===move.marbleId),tb=state.marbles.find(m=>m.id===move.targetMarbleId),sa=after.marbles.find(m=>m.id===move.marbleId),ta=after.marbles.find(m=>m.id===move.targetMarbleId);if(sb&&tb&&sa&&ta&&state.players.find(p=>p.id===tb.owner)!.team===enemy){const ourGain=strategicTrackValue(sa)-strategicTrackValue(sb),enemyGift=strategicTrackValue(ta)-strategicTrackValue(tb);score+=ourGain*18-enemyGift*28;if(relativeProgress(ta)>=FINISH_GATE_LOCAL_POSITION-3&&relativeProgress(tb)<FINISH_GATE_LOCAL_POSITION-3)score-=900;if(relativeProgress(ta)>=FINISH_GATE_LOCAL_POSITION-1&&relativeProgress(tb)<FINISH_GATE_LOCAL_POSITION-1)score-=1200;if(enemyGift>ourGain&&relativeProgress(sa)<FINISH_GATE_LOCAL_POSITION-11)score-=500;}const swing=enemyProgressLoss+progressGain;score+=swing*3;if(swing<=0)score-=220;}if(before.finish<8&&finishedCount(state,enemy)>=6)score+=threatRemoved*10+captures*70;if(score>bestScore){bestScore=score;best=move;}}
  return best;
}
